"""Initial migration

Revision ID: 19c94aa27f18
Revises: 
Create Date: 2025-08-23 15:34:38.780726

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '19c94aa27f18'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create catalog schema first
    op.execute('CREATE SCHEMA IF NOT EXISTS catalog')
    
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('category', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('image_file', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_modified_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    schema='catalog'
    )
    op.create_table('catalog_brands',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_modified_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_catalog_brands'))
    )
    op.create_table('catalog_categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_modified_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_catalog_categories'))
    )
    op.create_table('catalog_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('brand_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_modified_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['catalog_brands.id'], name=op.f('fk_catalog_items_brand_id_catalog_brands')),
    sa.ForeignKeyConstraint(['category_id'], ['catalog_categories.id'], name=op.f('fk_catalog_items_category_id_catalog_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_catalog_items'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('catalog_items')
    op.drop_table('catalog_categories')
    op.drop_table('catalog_brands')
    op.drop_table('products', schema='catalog')
    
    # Drop catalog schema
    op.execute('DROP SCHEMA IF EXISTS catalog CASCADE')
    # ### end Alembic commands ###
